package org.curioone.control.core;

import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.Reader;
import java.nio.charset.StandardCharsets;
import java.util.Properties;

/**
 * Global, static configuration for the CurioControl framework.
 *
 * <p>This class is the single place a team sets framework-wide behaviour that is not specific to
 * one subsystem: debug output, telemetry cadence, and feature toggles. It is deliberately static
 * and set once, early, from an OpMode's initialization hook.
 *
 * <p>Example:
 *
 * <pre>{@code
 * public void initRobot() {
 *     CurioConfig.DEBUG = true;
 *     CurioConfig.TELEMETRY_PERIOD_MILLIS = 500;
 *     robot = new CurioRobot(hardwareMap);
 * }
 * }</pre>
 *
 * <p><strong>Thread safety:</strong> this class is not thread-safe. Configure it from the OpMode
 * thread before the control loop starts, then treat it as read-only. Reading a value is a plain
 * field read and is safe from that same thread.
 *
 * <p>Public mutable static fields are intentional here and are the framework's documented
 * configuration surface. Every other class in CurioControl keeps its state private and reaches it
 * through accessors.
 *
 * @since 0.1.0
 */
@SuppressWarnings("checkstyle:VisibilityModifier")
public final class CurioConfig {

    /** Default flush interval: several times a second, not every loop. */
    private static final int DEFAULT_TELEMETRY_PERIOD_MILLIS = 200;

    /** Name of the build-metadata resource generated by the Gradle build. */
    private static final String VERSION_RESOURCE = "/org/curioone/control/version.properties";

    private static final String UNKNOWN_VERSION = "unknown";

    private static final String VERSION = loadVersion();

    /**
     * Emits {@code DEBUG}-category telemetry and verbose framework messages.
     *
     * <p>Off by default so a competition run stays quiet. Turning it on adds no measurable cost to
     * the control loop, but it does add console traffic.
     */
    public static boolean DEBUG = false;

    /**
     * Minimum interval, in milliseconds, between telemetry flushes.
     *
     * <p>Set to {@code 0} to flush every loop. Values below {@code 0} are treated as {@code 0}.
     */
    public static int TELEMETRY_PERIOD_MILLIS = DEFAULT_TELEMETRY_PERIOD_MILLIS;

    /**
     * Whether structured CSV logging is enabled.
     *
     * <p>Off by default: logging writes to Robot Controller storage and must be an explicit choice
     * so it can never interfere with a match.
     */
    public static boolean LOGGING_ENABLED = false;

    private CurioConfig() {
        throw new AssertionError(
                "CurioConfig is a static configuration holder and must not be instantiated.");
    }

    /**
     * Returns the version of CurioControl that the robot is running.
     *
     * <p>Teams can log this at the start of a match to record exactly which framework build a run
     * used. The value comes from the build itself, so it cannot drift from the published artifact.
     *
     * @return the framework version, for example {@code "0.1.0"}, or {@code "unknown"} if the build
     *     metadata is missing — for example when classes are loaded from a directory rather than a
     *     packaged jar
     */
    public static String version() {
        return VERSION;
    }

    private static String loadVersion() {
        try (InputStream in = CurioConfig.class.getResourceAsStream(VERSION_RESOURCE)) {
            if (in == null) {
                return UNKNOWN_VERSION;
            }
            final Properties properties = new Properties();
            try (Reader reader = new InputStreamReader(in, StandardCharsets.UTF_8)) {
                properties.load(reader);
            }
            return properties.getProperty("version", UNKNOWN_VERSION);
        } catch (IOException e) {
            return UNKNOWN_VERSION;
        }
    }
}
